#!/usr/bin/env python3
"""
Module: scripts/alert_system.py
Purpose: Sends email/console/file notifications for high-confidence predictions and high-value betting opportunities
Inputs:  data/betting/alerts.json (generated by betting system), data/betting/alerts_sent.json (deduplication log)
Outputs: Email notifications via SMTP, console output, alerts_sent.json (tracking)
Called by: scheduler.py (automated runs), manual CLI invocation
Depends on: config.settings (DATA_DIR)
"""

import json
import logging
import os
import smtplib
from datetime import datetime, timedelta
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from pathlib import Path
from typing import Dict, List, Optional

import sys
sys.path.insert(0, str(Path(__file__).parent.parent.parent))
from config.settings import DATA_DIR

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
log = logging.getLogger(__name__)

# =============================================================================
# CONFIGURATION
# =============================================================================

# Email settings (set via environment variables)
SMTP_HOST = os.environ.get("SMTP_HOST", "smtp.gmail.com")
SMTP_PORT = int(os.environ.get("SMTP_PORT", 587))
SMTP_USER = os.environ.get("SMTP_USER", "")
SMTP_PASS = os.environ.get("SMTP_PASS", "")
ALERT_EMAIL = os.environ.get("ALERT_EMAIL", "")

# Alert thresholds
MIN_CONFIDENCE_ALERT = "HIGH"  # Alert for HIGH and above
MIN_VALUE_ALERT = 0.08          # Alert for 8%+ edge

# Alert file path
ALERTS_FILE = DATA_DIR / "betting" / "alerts.json"
ALERTS_SENT_FILE = DATA_DIR / "betting" / "alerts_sent.json"


def load_alerts_sent() -> Dict:
    """Load record of sent alerts to avoid duplicates."""
    if ALERTS_SENT_FILE.exists():
        with open(ALERTS_SENT_FILE) as f:
            return json.load(f)
    return {}


def save_alerts_sent(sent: Dict):
    """Save sent alerts record."""
    ALERTS_SENT_FILE.parent.mkdir(exist_ok=True)
    with open(ALERTS_SENT_FILE, "w") as f:
        json.dump(sent, f, indent=2)


def was_alert_sent(alert_id: str) -> bool:
    """Check if alert was already sent."""
    sent = load_alerts_sent()
    return alert_id in sent


def mark_alert_sent(alert_id: str, method: str):
    """Mark alert as sent."""
    sent = load_alerts_sent()
    sent[alert_id] = {
        "sent_at": datetime.now().isoformat(),
        "method": method
    }
    save_alerts_sent(sent)


def send_email(subject: str, body: str, html_body: str = None) -> bool:
    """Send email notification.

    Args:
        subject: Email subject
        body: Plain text body
        html_body: Optional HTML body

    Returns:
        True if sent successfully
    """
    if not SMTP_USER or not SMTP_PASS or not ALERT_EMAIL:
        log.warning("Email not configured - set SMTP_USER, SMTP_PASS, ALERT_EMAIL env vars")
        return False

    try:
        msg = MIMEMultipart("alternative")
        msg["Subject"] = subject
        msg["From"] = SMTP_USER
        msg["To"] = ALERT_EMAIL

        # Add plain text
        msg.attach(MIMEText(body, "plain"))

        # Add HTML if provided
        if html_body:
            msg.attach(MIMEText(html_body, "html"))

        # Send
        with smtplib.SMTP(SMTP_HOST, SMTP_PORT) as server:
            server.starttls()
            server.login(SMTP_USER, SMTP_PASS)
            server.sendmail(SMTP_USER, ALERT_EMAIL, msg.as_string())

        log.info(f"Email sent: {subject}")
        return True

    except Exception as e:
        log.error(f"Failed to send email: {e}")
        return False


def save_alert_to_file(alert: Dict):
    """Save alert to file for external integrations."""
    ALERTS_FILE.parent.mkdir(exist_ok=True)

    # Load existing alerts
    alerts = []
    if ALERTS_FILE.exists():
        with open(ALERTS_FILE) as f:
            alerts = json.load(f)

    # Add new alert
    alerts.append(alert)

    # Keep only last 100 alerts
    alerts = alerts[-100:]

    with open(ALERTS_FILE, "w") as f:
        json.dump(alerts, f, indent=2)


def format_bet_alert(bet: Dict) -> tuple:
    """Format a bet alert as text and HTML.

    Returns:
        (plain_text, html) tuple
    """
    match = bet.get("match", "Unknown")
    prediction = bet.get("prediction", "Unknown")
    confidence = bet.get("confidence", "Unknown")
    value = bet.get("value_pct", 0)
    stake = bet.get("recommended_stake", 0)
    odds = bet.get("odds", 0)
    date = bet.get("date", "Unknown")
    factors = bet.get("factors", [])
    referee = bet.get("referee", "Not assigned")

    # Plain text
    text = f"""
HIGH-VALUE BET ALERT

Match: {match}
Date: {date}

Prediction: {prediction}
Confidence: {confidence}
Odds: {odds}
Value: {value}%

Recommended Stake: ${stake:.2f}
Potential Profit: ${stake * (odds - 1):.2f}

Factors: {', '.join(factors) if factors else 'None'}
Referee: {referee}

---
Generated by Serie A Betting AI
"""

    # HTML version
    html = f"""
<html>
<body style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
    <h2 style="color: #2e7d32;">HIGH-VALUE BET ALERT</h2>

    <div style="background: #f5f5f5; padding: 20px; border-radius: 10px; margin: 20px 0;">
        <h3 style="margin-top: 0;">{match}</h3>
        <p><strong>Date:</strong> {date}</p>

        <table style="width: 100%; border-collapse: collapse;">
            <tr>
                <td><strong>Prediction:</strong></td>
                <td>{prediction}</td>
            </tr>
            <tr>
                <td><strong>Confidence:</strong></td>
                <td style="color: #1565c0;">{confidence}</td>
            </tr>
            <tr>
                <td><strong>Odds:</strong></td>
                <td>{odds}</td>
            </tr>
            <tr>
                <td><strong>Value:</strong></td>
                <td style="color: #2e7d32; font-weight: bold;">{value}%</td>
            </tr>
        </table>
    </div>

    <div style="background: #e8f5e9; padding: 20px; border-radius: 10px; margin: 20px 0;">
        <h4 style="margin-top: 0; color: #2e7d32;">Recommendation</h4>
        <p><strong>Stake:</strong> ${stake:.2f}</p>
        <p><strong>Potential Profit:</strong> ${stake * (odds - 1):.2f}</p>
    </div>

    <div style="font-size: 12px; color: #666; margin-top: 20px;">
        <p><strong>Factors:</strong> {', '.join(factors) if factors else 'None'}</p>
        <p><strong>Referee:</strong> {referee}</p>
    </div>

    <hr style="border: none; border-top: 1px solid #ddd; margin: 20px 0;">
    <p style="font-size: 11px; color: #999;">
        Generated by Serie A Betting AI | {datetime.now().strftime('%Y-%m-%d %H:%M')}
    </p>
</body>
</html>
"""

    return text, html


def format_summary_alert(stats: Dict, bets: List[Dict]) -> tuple:
    """Format weekly summary as text and HTML.

    Returns:
        (plain_text, html) tuple
    """
    text = f"""
WEEKLY PERFORMANCE SUMMARY

Period: Last 7 days

RESULTS:
- Total Bets: {stats.get('total_bets', 0)}
- Win Rate: {stats.get('win_rate', 0)}%
- ROI: {stats.get('roi', 0)}%
- Profit: ${stats.get('total_profit', 0):.2f}

UPCOMING BETS:
"""
    for bet in bets[:5]:
        text += f"- {bet.get('match')}: {bet.get('prediction')} @ {bet.get('odds')} | Value: {bet.get('value_pct', 0)}%\n"

    text += """
---
Generated by Serie A Betting AI
"""

    html = f"""
<html>
<body style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
    <h2>WEEKLY PERFORMANCE SUMMARY</h2>

    <div style="background: #f5f5f5; padding: 20px; border-radius: 10px;">
        <h3>Results (Last 7 Days)</h3>
        <table style="width: 100%;">
            <tr><td>Total Bets:</td><td><strong>{stats.get('total_bets', 0)}</strong></td></tr>
            <tr><td>Win Rate:</td><td><strong>{stats.get('win_rate', 0)}%</strong></td></tr>
            <tr><td>ROI:</td><td style="color: {'#2e7d32' if stats.get('roi', 0) > 0 else '#c62828'};">
                <strong>{stats.get('roi', 0)}%</strong></td></tr>
            <tr><td>Profit:</td><td style="color: {'#2e7d32' if stats.get('total_profit', 0) > 0 else '#c62828'};">
                <strong>${stats.get('total_profit', 0):.2f}</strong></td></tr>
        </table>
    </div>

    <div style="margin-top: 20px;">
        <h3>Upcoming Recommended Bets</h3>
        <ul>
"""
    for bet in bets[:5]:
        html += f"<li>{bet.get('match')}: {bet.get('prediction')} @ {bet.get('odds')} | Value: {bet.get('value_pct', 0)}%</li>"

    html += """
        </ul>
    </div>
</body>
</html>
"""

    return text, html


def check_and_send_alerts():
    """Check for new high-value opportunities and send alerts."""
    log.info("Checking for alert-worthy opportunities...")

    # Load betting slip
    slip_path = DATA_DIR / "betting" / "betting_slip.json"
    if not slip_path.exists():
        log.info("No betting slip found")
        return

    with open(slip_path) as f:
        slip = json.load(f)

    # Check recommended bets
    recommended = slip.get("recommended_singles", [])
    alerts_to_send = []

    for bet in recommended:
        # Check if meets alert threshold
        value = bet.get("value_pct", 0)
        confidence = bet.get("confidence", "LOW")

        if value >= MIN_VALUE_ALERT * 100:  # Convert to percentage
            alert_id = f"{bet['match']}_{bet['date']}_{bet['prediction']}"

            if not was_alert_sent(alert_id):
                alerts_to_send.append(bet)

    if not alerts_to_send:
        log.info("No new alerts to send")
        return

    # Send alerts
    for bet in alerts_to_send:
        alert_id = f"{bet['match']}_{bet['date']}_{bet['prediction']}"

        # Console alert
        print("\n" + "!" * 60)
        print(" HIGH-VALUE BET ALERT!")
        print("!" * 60)
        print(f"  {bet['match']}: {bet['prediction']} @ {bet['odds']}")
        print(f"  Value: {bet['value_pct']}% | Stake: ${bet['recommended_stake']:.2f}")
        print("!" * 60 + "\n")

        # Save to file
        alert_record = {
            "id": alert_id,
            "type": "high_value_bet",
            "created_at": datetime.now().isoformat(),
            "bet": bet
        }
        save_alert_to_file(alert_record)

        # Send email
        text, html = format_bet_alert(bet)
        subject = f"[BET ALERT] {bet['match']}: {bet['prediction']} - {bet['value_pct']}% VALUE"

        if send_email(subject, text, html):
            mark_alert_sent(alert_id, "email")
        else:
            mark_alert_sent(alert_id, "console_only")

        log.info(f"Alert sent for {bet['match']}")

    log.info(f"Sent {len(alerts_to_send)} alerts")


def send_weekly_summary():
    """Send weekly performance summary."""
    log.info("Generating weekly summary...")

    # Load performance stats
    try:
        from features.bankroll_manager import get_performance_stats, load_history
    except ImportError:
        from bankroll_manager import get_performance_stats, load_history

    stats = get_performance_stats()

    # Load current betting slip
    slip_path = DATA_DIR / "betting" / "betting_slip.json"
    recommended = []
    if slip_path.exists():
        with open(slip_path) as f:
            slip = json.load(f)
        recommended = slip.get("recommended_singles", [])

    # Format and send
    text, html = format_summary_alert(stats, recommended)
    subject = f"[WEEKLY SUMMARY] Win Rate: {stats.get('win_rate', 0)}% | ROI: {stats.get('roi', 0)}%"

    # Console output
    print(text)

    # Email
    if send_email(subject, text, html):
        log.info("Weekly summary sent")
    else:
        log.info("Weekly summary generated (email not configured)")


def test_email():
    """Test email configuration."""
    subject = "[TEST] Serie A Betting AI Alert System"
    body = "This is a test alert from your Serie A Betting AI system."
    html = """
    <html>
    <body>
        <h2>Test Alert</h2>
        <p>This is a test alert from your Serie A Betting AI system.</p>
        <p>If you receive this, your email configuration is working!</p>
    </body>
    </html>
    """

    if send_email(subject, body, html):
        print("Test email sent successfully!")
    else:
        print("Failed to send test email. Check configuration:")
        print(f"  SMTP_HOST: {SMTP_HOST}")
        print(f"  SMTP_PORT: {SMTP_PORT}")
        print(f"  SMTP_USER: {'SET' if SMTP_USER else 'NOT SET'}")
        print(f"  SMTP_PASS: {'SET' if SMTP_PASS else 'NOT SET'}")
        print(f"  ALERT_EMAIL: {'SET' if ALERT_EMAIL else 'NOT SET'}")


def main():
    """Main entry point."""
    import argparse

    parser = argparse.ArgumentParser(description="Alert System")
    parser.add_argument("--test", action="store_true", help="Test email configuration")
    parser.add_argument("--summary", action="store_true", help="Send weekly summary")
    args = parser.parse_args()

    if args.test:
        test_email()
    elif args.summary:
        send_weekly_summary()
    else:
        check_and_send_alerts()


if __name__ == "__main__":
    main()
